<a href="https://colab.research.google.com/github/karanbhatt1/MachineLearning/blob/main/EmailClassification_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import *
from sklearn.naive_bayes import *
from sklearn.model_selection import train_test_split

In [ ]:
df  = pd.read_csv('emails.csv')

In [ ]:
df

In [ ]:
df.head(10)

In [ ]:
df.shape

In [ ]:
df['text'][0]

In [ ]:
df.isna().sum()

text    0
spam    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(33)

In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
df.shape

(5695, 2)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
vectorizer = CountVectorizer()

In [30]:
vectorized_input_data = vectorizer.fit_transform(df['text'])

In [31]:
vectorized_input_data.shape

(5695, 37303)

In [34]:
vectorcol = vectorizer.get_feature_names_out()

In [39]:
vectorcol[5000:5100]

array(['antaeus', 'antagonism', 'antarctic', 'ante', 'anteilsverwaltung',
       'antenna', 'antes', 'anther', 'anthony', 'anthropoid',
       'anthropology', 'anti', 'anticipate', 'anticipated', 'anticipates',
       'anticipating', 'anticipation', 'anticipitory', 'anticlimax',
       'anticompetitive', 'antigo', 'antil', 'antilbkk', 'antiperspirant',
       'antique', 'antiques', 'antisanctions', 'antitank', 'antitrust',
       'antivirus', 'antly', 'anto', 'antonella', 'antonio', 'antonioacm',
       'antonioantonio', 'antonioantoniomc', 'antoniobdantas', 'antoniop',
       'antoniopilurzo', 'antunes', 'anunauthorized', 'anurag',
       'anvasetc', 'anvil', 'anw', 'anway', 'anxious', 'anxiously', 'any',
       'anybody', 'anyhgh', 'anyhow', 'anymore', 'anyone', 'anything',
       'anythingforyou', 'anytime', 'anyway', 'anyways', 'anywhere',
       'anz', 'ao', 'aobeb', 'aoberg', 'aof', 'aofarachain', 'aol',
       'aomori', 'aonp', 'aoq', 'ap', 'apa', 'apache', 'apachi',
       'aparently', 'aparna', 'apart', 'apartheid', 'aparticular',
       'apartment', 'apartments', 'apartner', 'apc', 'aperture', 'apex',
       'apfa', 'aph', 'aphrodite', 'api', 'apiculture', 'apk', 'apl',
       'aplan', 'apo', 'apodaca', 'apodal', 'apollo', 'apologetic',
       'apologies'], dtype=object)

In [ ]:
df['spam'].value_counts() # check for imbalance data

spam
0    4327
1    1368
Name: count, dtype: int64

In [40]:
X = vectorized_input_data
y = df['spam']

In [41]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y                  )

In [42]:
base_model = MultinomialNB()

In [43]:
mdl = base_model.fit(x_train,y_train)

In [45]:
predictions = mdl.predict(x_test)

In [58]:
Emails = ['We are Happy to tell that you are elligible for pay later program.Come Fast and acquire the advantage',
          "Hey, Lets have a quick meeting tommorow morning at 10 AM. Do join 5 min prior to meeting."]

In [59]:
vecotremail = vectorizer.transform(Emails)

In [60]:
y_test

2464    0
1078    1
5640    0
3321    0
2654    0
       ..
1693    0
1325    1
5290    0
3538    0
1957    0
Name: spam, Length: 1139, dtype: int64

In [64]:
prediction = mdl.predict(vecotremail)
print(prediction)
for i in range(len(Emails)):
  if(prediction[i] == 1):
      print('Spam Mail')
  else:
      print('not spam Mail')

[1 0]
Spam Mail
not spam Mail

In [44]:
roc_auc_score(y_test,mdl.predict(x_test))

np.float64(0.9923041221889372)